
import React, { useState, createContext, useContext, useEffect } from 'react';
import { GlobalSettings } from '../types';

export interface GlobalSettingsContextType {
  settings: GlobalSettings;
  updateSettings: (newSettings: Partial<GlobalSettings>) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

export const GlobalSettingsContext = createContext<GlobalSettingsContextType | null>(null);

const DEFAULT_SETTINGS: GlobalSettings = {
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    numberFormat: 'comma_decimal',
    language: 'es',
    fontSize: 'md',
};

// --- Translations Dictionary ---
export const TRANSLATIONS = {
    es: {
        // Common
        'common.save': 'Guardar',
        'common.cancel': 'Cancelar',
        'common.edit': 'Editar',
        'common.delete': 'Eliminar',
        'common.create': 'Crear',
        'common.search': 'Buscar',
        'common.actions': 'Acciones',
        'common.name': 'Nombre',
        'common.email': 'Email',
        'common.phone': 'Teléfono',
        'common.address': 'Dirección',
        'common.accept': 'Aceptar',
        'common.confirm': 'Confirmar',
        'common.status': 'Estado',
        'common.notes': 'Notas',
        'common.yes': 'Sí',
        'common.no': 'No',
        'common.import_ai': 'Importar con IA',
        'common.previous': 'Anterior',
        'common.next': 'Siguiente',
        'common.page_of': 'Página {current} de {total}',
        'common.today': 'Hoy',
        'common.error': 'Error',
        'common.date': 'Fecha',
        'common.total': 'Total',
        'common.client': 'Cliente',
        'common.add': 'Añadir',
        'common.update': 'Actualizar',
        'common.loading': 'Cargando...',
        'common.go_back': 'Volver',
        'common.hours': 'horas',

        // Dashboard Home
        'dashboard.welcome': 'Bienvenido a Pazzi',
        'dashboard.select_module': 'Selecciona un módulo para comenzar a trabajar.',
        'dashboard.quick_access': 'Accesos Rápidos',
        'dashboard.desc.tienda': 'Gestión de productos, clientes, inventario y sucursales.',
        'dashboard.desc.pm': 'Gestión de proyectos, recursos y cronogramas.',
        'dashboard.desc.pos': 'Punto de venta, caja y facturación.',
        'dashboard.desc.ecommerce': 'Administración de tienda online y pedidos.',
        'dashboard.desc.admin': 'Configuración global y alertas.',
        'dashboard.desc.client': 'Portal de cliente.',
        'dashboard.access_btn': 'Accede a las herramientas de {module}',
        
        // Dashboard Tour
        'tour.step1.title': 'Bienvenido a Pazzi',
        'tour.step1.content': 'Este es un breve recorrido por los módulos principales. Usa el selector de módulos o el menú lateral para navegar.',
        'tour.step2.title': 'Gestión de Proyectos',
        'tour.step2.content': 'Administra proyectos, clientes, recursos, calendarios y comunicación.',
        'tour.step3.title': 'Punto de Venta (POS)',
        'tour.step3.content': 'Realiza ventas, gestiona tu caja, inventario y reportes en tienda.',
        'tour.step4.title': 'Administración E-commerce',
        'tour.step4.content': 'Configura tu tienda online, gestiona productos web y pedidos.',
        'tour.step5.title': '¡Todo Listo!',
        'tour.step5.content': 'Has completado el tour. ¡Explora Pazzi y descubre todo lo que puede hacer por tu negocio!',
        'tour.skip': 'Saltar Tour',
        'tour.finish': 'Finalizar',

        // Admin Dashboard
        'admin.dashboard.title': 'Panel de Administración',
        'admin.dashboard.subtitle': 'Configure las opciones globales y las alertas del sistema.',
        
        // Navbar & User Menu
        'nav.my_account': 'Mi Cuenta',
        'nav.configuration': 'Configuración',
        'nav.logout': 'Cerrar Sesión',
        'nav.my_orders': 'Mis Pedidos',

        // Modules Names
        'Tienda': 'Tienda',
        'Gestión de Proyectos': 'Gestión de Proyectos',
        'Punto de Venta': 'Punto de Venta',
        'E-commerce': 'E-commerce',
        'Administración': 'Administración',
        'Portal Cliente': 'Portal Cliente',

        // Submodules Names
        'Productos': 'Productos',
        'Inventario': 'Inventario',
        'Categorías': 'Categorías',
        'Departamentos': 'Departamentos',
        'Clientes': 'Clientes',
        'Colaboradores': 'Colaboradores',
        'Sucursales': 'Sucursales',
        'Dashboard PM': 'Dashboard PM',
        'Proyectos': 'Proyectos',
        'Chat de Proyectos': 'Chat de Proyectos',
        'Calendario': 'Calendario',
        'Reportes PM': 'Reportes PM',
        'Caja Registradora': 'Caja Registradora',
        'Reportes POS': 'Reportes POS',
        'Historial de Ventas': 'Historial de Ventas',
        'Estimados': 'Estimados',
        'Apartados (Layaway)': 'Apartados (Layaway)',
        'Cuentas por Cobrar': 'Cuentas por Cobrar',
        'Cuentas por Pagar': 'Cuentas por Pagar',
        'Config. Cajas': 'Config. Cajas',
        'Dashboard E-commerce': 'Dashboard E-commerce',
        'Pedidos Online': 'Pedidos Online',
        'Proveedores': 'Proveedores',
        'Pedidos a Proveedor': 'Pedidos a Proveedor',
        'Mi Tienda (Vista Previa)': 'Mi Tienda (Vista Previa)',
        'Dashboard Admin': 'Dashboard Admin',
        'Dashboard Cliente': 'Dashboard Cliente',
        'Calendario Proyecto': 'Calendario Proyecto',
        'Chat del Proyecto': 'Chat del Proyecto',
        
        // Quick Links
        'quick.create_product': 'Crear Producto',
        'quick.sales_history': 'Historial de Ventas',
        'quick.view_projects': 'Ver Proyectos',
        'quick.view_inventory': 'Ver Inventario',
        'quick.go_to_pos': 'Ir a Caja',
        'quick.my_projects': 'Mis Proyectos',

        // PM Dashboard Specifics
        'pm.dashboard.title': 'Dashboard de Proyectos',
        'pm.dashboard.subtitle': 'Un resumen de la actividad reciente y próxima.',
        'pm.dashboard.view_all': 'Ver Todos los Proyectos',
        'pm.dashboard.full_calendar': 'Calendario Completo',
        'pm.stats.active': 'Proyectos Activos',
        'pm.stats.pending': 'Proyectos Pendientes',
        'pm.stats.completed_month': 'Completados (Este Mes)',
        'pm.section.in_progress': 'Proyectos en Curso o Próximos',
        'pm.section.visits': 'Próximas Visitas',
        'pm.section.top_clients': 'Top Clientes (Este Mes)',
        'pm.section.recent_chat': 'Actividad Reciente en Chats',
        'pm.section.top_employees': 'Colaboradores más Activos (Este Mes)',
        'pm.no_client': 'Sin cliente asignado',
        'pm.view_chat': 'Ver Chat',
        'pm.no_active_projects': 'No hay proyectos activos o por iniciar próximamente.',
        'pm.general_visit': 'Visita General',
        'pm.no_visits': 'No hay visitas programadas.',
        'pm.no_sales': 'No hay datos de ventas de clientes este mes.',
        'pm.no_messages': 'No hay mensajes recientes.',
        'pm.no_hours': 'No hay horas de visita registradas este mes.',
        
        // Project Detail
        'project.detail.back': 'Volver a Proyectos',
        'project.detail.not_found': 'Proyecto no encontrado',
        'project.detail.not_found_desc': 'El proyecto que buscas no existe o ha sido eliminado.',
        'project.detail.back_list': 'Volver a la lista de proyectos',
        'project.detail.create_title': 'Crear Nuevo Proyecto',
        
        // Tasks
        'tasks.status.todo': 'Tareas por realizar',
        'tasks.status.in_progress': 'En progreso',
        'tasks.status.for_approval': 'Para aprobar',
        'tasks.status.done': 'Hecho',
        'tasks.add_placeholder': 'Escriba un título para esta tarea...',
        'tasks.add_btn': 'Añadir Tarea',
        'tasks.add_trigger': 'Añadir una tarea',
        'tasks.detail.title': 'Detalles de la Tarea',
        'tasks.detail.field_title': 'Título',
        'tasks.detail.field_desc': 'Descripción',
        'tasks.detail.desc_placeholder': 'Añada una descripción más detallada...',
        'tasks.detail.assignees': 'Asignar Colaboradores',
        'tasks.detail.comments': 'Comentarios',
        'tasks.detail.no_comments': 'No hay comentarios.',
        'tasks.detail.comment_placeholder': 'Añadir un comentario...',
        'tasks.detail.archive': 'Archivar Tarea',
        'tasks.detail.confirm_archive': '¿Está seguro que desea archivar esta tarea?',

        // Inventory Page
        'inventory.title': 'Gestión de Inventario',
        'inventory.search_placeholder': 'Buscar por nombre o SKU...',
        'inventory.filter.all_categories': 'Todas las Categorías',
        'inventory.col.product': 'Producto',
        'inventory.col.total_stock': 'Stock Total',
        'inventory.action.history': 'Historial',
        'inventory.action.adjust': 'Ajustar Stock',
        
        // Inventory History
        'inventory.history.title': 'Historial de Inventario: {product}',
        'inventory.history.current_stock_branch': 'Stock Actual por Sucursal',
        'inventory.history.total': 'Total',
        'inventory.history.movement_log': 'Registro de Movimientos por Sucursal',
        'inventory.history.col_date': 'Fecha',
        'inventory.history.col_type': 'Tipo',
        'inventory.history.col_change': 'Cambio',
        'inventory.history.col_stock_before': 'Stock Antes',
        'inventory.history.col_stock_after': 'Stock Después',
        'inventory.history.col_ref': 'Ref.',
        'inventory.history.col_notes': 'Notas',
        'inventory.history.col_employee': 'Empleado',
        'inventory.history.no_movements': 'No hay movimientos registrados para este producto en esta sucursal.',

        // Stock Adjustment
        'inventory.adjust.title': 'Gestionar Stock de: {product}',
        'inventory.adjust.single_title': 'Ajustar Stock - {product}',
        'inventory.adjust.adjusting_for': 'Ajustando stock para {product} en la sucursal {branch}.',
        'inventory.adjust.stock_in_branch': 'Stock en sucursal ({branch})',
        'inventory.adjust.total_stock_all': 'Stock Total (todas las sucursales)',
        'inventory.adjust.help_text': 'Ingrese la cantidad a sumar (ej: 10 o +10) o restar (ej: -5) para cada sucursal. Deje en blanco si no hay cambios.',
        'inventory.adjust.col_branch': 'Sucursal',
        'inventory.adjust.col_current': 'Stock Actual',
        'inventory.adjust.col_adjust': 'Ajuste (+/-)',
        'inventory.adjust.col_new': 'Nuevo Stock',
        'inventory.adjust.col_notes': 'Notas',
        'inventory.adjust.save': 'Guardar Ajustes',
        'inventory.adjust.save_btn': 'Guardar Ajuste',
        'inventory.adjust.add_subtract': 'Sumar o Restar Stock',
        'inventory.adjust.input_placeholder': 'Ej: +10, -5, 25',
        'inventory.adjust.input_help': 'Ingrese la cantidad a sumar (ej: 10 o +10) o restar (ej: -5).',
        'inventory.adjust.new_stock': 'Nuevo Stock en Sucursal',
        'inventory.adjust.reason_label': 'Notas / Razón (Opcional pero Recomendado)',
        'inventory.adjust.reason_placeholder': 'Ej: Conteo físico, producto dañado, transferencia...',

        // Categories
        'category.list.title': 'Gestión de Categorías',
        'category.list.create': 'Crear Categoría',
        'category.form.create': 'Crear Categoría',
        'category.form.edit': 'Editar Categoría',
        'category.field.name': 'Nombre de la Categoría',

        // Departments
        'department.list.title': 'Gestión de Departamentos',
        'department.list.create': 'Crear Departamento',
        'department.form.create': 'Crear Departamento',
        'department.form.edit': 'Editar Departamento',
        'department.field.name': 'Nombre del Departamento',

        // Branches
        'branch.list.title': 'Gestión de Sucursales',
        'branch.list.create': 'Crear Sucursal',
        'branch.form.create': 'Crear Sucursal',
        'branch.form.edit': 'Editar Sucursal',
        'branch.field.name': 'Nombre de la Sucursal',
        'branch.field.address': 'Dirección',
        'branch.field.phone': 'Teléfono',
        'branch.field.active': 'Sucursal Activa',

        // Employees
        'employee.list.title': 'Gestión de Colaboradores',
        'employee.list.create': 'Crear Colaborador',
        'employee.form.create': 'Crear Colaborador',
        'employee.form.edit': 'Editar Colaborador',
        'employee.field.name': 'Nombre',
        'employee.field.lastname': 'Apellido',
        'employee.field.email': 'Email',
        'employee.field.role': 'Rol',
        'employee.field.phone': 'Teléfono',
        'employee.field.address': 'Dirección',
        'employee.tab.personal': 'Personal',
        'employee.tab.access': 'Acceso y Empleo',
        'employee.tab.permissions': 'Permisos',
        'employee.tab.info': 'Información Adicional',

        // Clients
        'client.list.title': 'Gestión de Clientes',
        'client.list.create': 'Crear Cliente',
        'client.form.create': 'Crear Cliente',
        'client.form.edit': 'Modificar Cliente',
        'client.field.lastname': 'Apellido',
        'client.field.type': 'Tipo',
        'client.field.company': 'Empresa',
        'client.field.city': 'Ciudad',
        'client.field.country': 'País',
        'client.field.zip': 'Zip',
        'client.field.fax': 'Fax',
        'client.field.contact_person': 'Persona de Contacto',
        'client.field.ssn': 'Seguro Social',
        'client.field.dob': 'Fecha Nacimiento',
        'client.field.projects': 'Proyectos Asociados',
        'client.field.projects_hint': 'Mantenga presionado Ctrl (o Cmd en Mac) para seleccionar múltiples proyectos.',
        'client.tab.general': 'General',
        'client.tab.taxes': 'Impuestos',
        'client.tab.billing': 'Facturación',
        'client.tab.payments': 'Cobros',
        'client.tab.shipping': 'Envío',
        'client.tab.loyalty': 'Lealtad',
        'client.tab.photo': 'Foto',
        
        // Client Tabs Details
        'client.taxes.responsibility': 'Responsabilidad Contributiva',
        'client.taxes.state': 'Estatal (%)',
        'client.taxes.municipal': 'Municipal (%)',
        'client.taxes.tax_id': 'ID Fiscal (RFC/NIF)',
        'client.taxes.exemption': 'Exención IVU Municipal - Válido Hasta',
        'client.billing.address': 'Dirección de Facturación',
        'client.billing.special_msg': 'Mensaje Especial en la Factura',
        'client.billing.special_msg_hint': 'El mensaje se puede configurar en: Mantenimiento - Opciones.',
        'client.billing.charge_type': 'Tipo de Cobro Acordado',
        'client.billing.discount_price': 'Descuento al Precio',
        'client.billing.markup_cost': 'Sobre el Costo',
        'client.billing.code': 'Contraseña/Código',
        'client.payments.balance': 'Balance',
        'client.payments.credit_limit': 'Límite Crédito',
        'client.payments.terms': 'Términos',
        'client.payments.category': 'Categoría',
        'client.payments.salesperson': 'Vendedor',
        'client.payments.price_level': 'Nivel de Precios',
        'client.payments.business_type': 'Tipo de Negocio',
        'client.payments.zone': 'Zona',
        'client.payments.show_balance': 'Ver Balance',
        'client.shipping.address': 'Dirección de Envío',
        'client.shipping.contact_name': 'Nombre Contacto Envío',
        'client.shipping.contact_phone': 'Teléfono Contacto Envío',
        'client.shipping.carrier': 'Transportista Preferido',
        'client.loyalty.points': 'Puntos de Lealtad',
        'client.loyalty.level': 'Nivel de Lealtad',
        'client.photo.add_url': 'Añadir URL de Imagen',

        // Projects
        'project.list.title': 'Gestión de Proyectos',
        'project.list.create': 'Crear Proyecto',
        'project.form.create': 'Crear Proyecto',
        'project.form.edit': 'Editar Proyecto',
        'project.tab.details': 'Detalles',
        'project.tab.schedule': 'Programación',
        'project.tab.resources': 'Recursos',
        'project.tab.invoicing': 'Facturación',
        'project.tab.chat': 'Chat del Proyecto',
        'project.tab.tasks': 'Tareas',
        'project.field.name': 'Nombre del Proyecto',
        'project.field.client': 'Cliente',
        'project.field.status': 'Estado',
        'project.field.description': 'Descripción',
        'project.field.team': 'Equipo Asignado',
        'project.field.next_visit': 'Próxima Visita',
        
        // Project Schedule
        'project.schedule.initial_visit': 'Visita Inicial',
        'project.schedule.visit_date': 'Fecha Visita',
        'project.schedule.visit_time': 'Hora Visita',
        'project.schedule.work_type': 'Trabajo del Proyecto',
        'project.schedule.mode.days_only': 'Solo Días',
        'project.schedule.mode.days_times': 'Días y Horas',
        'project.schedule.mode.range': 'Rango Continuo',
        'project.schedule.add_work_day': 'Añadir Día de Trabajo',
        'project.schedule.start_time': 'Hora Inicio',
        'project.schedule.end_time': 'Hora Fin',
        'project.schedule.add_range': 'Añadir Rango',
        'project.schedule.range_start': 'Fecha Inicio Rango',
        'project.schedule.range_end': 'Fecha Fin Rango',

        // Project Resources
        'project.resources.assign_catalog': 'Asignar Productos del Catálogo',
        'project.resources.add_custom_title': 'Añadir Producto/Servicio Personalizado',
        'project.resources.quantity': 'Cantidad',
        'project.resources.unit_price_opt': 'Precio Unit. (Opc)',
        'project.resources.add_custom_btn': 'Añadir Personalizado',
        'project.resources.assign_employees': 'Asignar Empleados',
        'project.resources.custom_name': 'Nombre (ej. Material Extra)',

        // POS
        'pos.title': 'Caja Principal',
        'pos.emergency_mode': 'Modo Emergencia',
        'pos.clear_cart': 'Borrar',
        'pos.hold_cart': 'Espera',
        'pos.client': 'Cliente',
        'pos.payout': 'Desembolso',
        'pos.return': 'Devolución',
        'pos.estimate': 'Estimado',
        'pos.layaway': 'Apartado',
        'pos.reprint': 'Reimprimir',
        'pos.close_shift': 'Cerrar Turno',
        'pos.user': 'Usuario',
        'pos.pay': 'Pagar',
        'pos.total': 'TOTAL',
        'pos.subtotal': 'Subtotal',
        'pos.tax': 'IVA',
        'pos.search_placeholder': 'Buscar por SKU, Código Barras o Nombre',
        'pos.empty_cart': 'El carrito está vacío',
        'pos.client_search': 'Buscar / Asignar Cliente',
        'pos.new_project': 'Nuevo Proyecto',
        'pos.header.external': 'EXTERNA',
        
        // POS Sales History
        'pos.sales_history.title': 'Historial de Ventas POS',
        'pos.sales_history.col.id': 'ID Venta',
        'pos.sales_history.col.date': 'Fecha',
        'pos.sales_history.col.total': 'Total',
        'pos.sales_history.col.items': 'Items',
        'pos.sales_history.col.method': 'Método Pago',
        'pos.sales_history.col.cashier': 'Cajero',
        'pos.sales_history.col.register': 'ID Caja',
        'pos.sales_history.print_receipt': 'Imprimir Recibo',

        // POS Estimates
        'pos.estimates.title': 'Gestión de Estimados',
        'pos.estimates.create': 'Crear Estimado',
        'pos.estimates.combine': 'Combinar',
        'pos.estimates.col.id': 'ID Estimado',
        'pos.estimates.col.date': 'Fecha',
        'pos.estimates.col.client': 'Cliente',
        'pos.estimates.col.total': 'Total',
        'pos.estimates.col.status': 'Estado',
        'pos.estimates.form.create_title': 'Crear Estimado',
        'pos.estimates.form.edit_title': 'Editar Estimado',
        'pos.estimates.form.add_products': 'Añadir Productos',
        'pos.estimates.form.status': 'Estado',
        'pos.estimates.form.valid_until': 'Válido Hasta (Opcional)',
        'pos.estimates.form.notes': 'Notas',
        'pos.estimates.print_pdf': 'Imprimir PDF',
        'pos.estimates.confirm_combine.title': 'Confirmar Combinación de Estimados',
        'pos.estimates.confirm_combine.message': '¿Está seguro de que desea combinar {count} estimados en uno nuevo? Los estimados originales se marcarán como "Combinado".',

        // POS Layaways
        'pos.layaways.title': 'Gestión de Apartados (Layaway)',
        'pos.layaways.col.id': 'ID Apartado',
        'pos.layaways.col.date': 'Fecha',
        'pos.layaways.col.client': 'Cliente',
        'pos.layaways.col.total': 'Total',
        'pos.layaways.col.paid': 'Pagado',
        'pos.layaways.col.balance': 'Balance',
        'pos.layaways.col.status': 'Estado',
        'pos.layaways.register_payment': 'Registrar Abono',
        'pos.layaways.mark_completed': 'Marcar como Completado/Entregado',
        'pos.layaways.cancel': 'Cancelar Apartado',
        'pos.layaways.confirm_cancel.title': 'Confirmar Cancelación de Apartado',
        'pos.layaways.confirm_cancel.message': '¿Está seguro de que desea cancelar el apartado #{id}? El stock NO será devuelto automáticamente.',
        'pos.layaways.confirm_complete.title': 'Confirmar Completado',
        'pos.layaways.confirm_complete.message': '¿Marcar el apartado #{id} como completado y entregado?',
        
        // POS Accounts Receivable
        'pos.receivable.title': 'Cuentas por Cobrar',
        'pos.receivable.filter': 'Filtrar:',
        'pos.receivable.filter.pending': 'Pendientes',
        'pos.receivable.filter.paid': 'Pagadas',
        'pos.receivable.filter.all': 'Todas',
        'pos.receivable.col.id': 'ID Venta',
        'pos.receivable.col.date': 'Fecha Venta',
        'pos.receivable.col.due_date': 'Vencimiento',
        'pos.receivable.col.client': 'Cliente',
        'pos.receivable.col.total': 'Monto Total',
        'pos.receivable.col.paid': 'Monto Pagado',
        'pos.receivable.col.balance': 'Saldo',
        'pos.receivable.col.status': 'Estado',
        'pos.receivable.action.reminder': 'Enviar Recordatorio',
        'pos.receivable.action.edit': 'Editar Detalles',
        'pos.receivable.action.print': 'Imprimir Cuenta',
        'pos.receivable.action.payment': 'Registrar Abono',
        'pos.receivable.action.void': 'Anular Cuenta',
        'pos.receivable.payment_modal.title': 'Registrar Abono para Venta #{id}',
        'pos.receivable.payment_modal.balance': 'Balance pendiente',
        'pos.receivable.payment_modal.amount': 'Monto del Abono',
        'pos.receivable.payment_modal.method': 'Método de Pago',
        'pos.receivable.payment_modal.reference': 'Nº de Factura/Referencia (Opcional)',
        'pos.receivable.payment_modal.attachment': 'Adjuntar Comprobante (Opcional)',
        'pos.receivable.payment_modal.register': 'Registrar Abono',
        'pos.receivable.edit_modal.title': 'Editar Cuenta por Cobrar - Venta #{id}',
        'pos.receivable.edit_modal.client': 'Cliente',
        'pos.receivable.edit_modal.original_amount': 'Monto Original',
        'pos.receivable.edit_modal.due_date': 'Fecha de Vencimiento',
        'pos.receivable.edit_modal.notes': 'Notas de Cobranza',
        'pos.receivable.confirm_reminder.title': 'Enviar Notificación de Cobro',
        'pos.receivable.confirm_reminder.message': '¿Está seguro de que desea enviar un mensaje de notificación de cobro al cliente {client}?',
        'pos.receivable.confirm_reminder.btn': 'Sí, Enviar Mensaje',
        'pos.receivable.confirm_void.title': 'Confirmar Anulación',
        'pos.receivable.confirm_void.message': '¿Seguro que desea anular la cuenta por cobrar {id}?',
        'pos.receivable.confirm_void.btn': 'Sí, Anular',

        // Product Page & Modal
        'product.list.title': 'Gestión de Productos',
        'product.list.add': 'Agregar Producto',
        'product.list.import_ai': 'Importar con IA',
        'product.form.title.create': 'Crear Producto',
        'product.form.title.edit': 'Modificar Inventario',
        'product.tab.main': 'Principal',
        'product.tab.inventory': 'Inventario y Precios',
        'product.tab.identification': 'Identificación',
        'product.tab.classification': 'Clasificación',
        'product.tab.specs': 'Especificaciones',
        'product.tab.prices': 'Niveles de Precio',
        'product.tab.variations': 'Variaciones',
        'product.tab.pos': 'Configuración POS',
        'product.field.name': 'Nombre',
        'product.field.sku': 'Referencia (SKU)',
        'product.field.barcode': 'Código Barras',
        'product.field.price': 'Precio Base',
        'product.field.cost': 'Costo',
        'product.field.profit': 'Ganancia',
        'product.field.inventory': 'Inventario',
        'product.field.available': 'Disponible',
        'product.field.category': 'Categoría',
        'product.field.description': 'Descripción',
        'product.field.active': 'Activo',
        'product.field.service': 'Servicio',
        'product.field.supplier_code': 'Cód. Fact. Suplidor',
        'product.field.chain_code': 'Código Cadena',
        'product.field.other_skus': 'Otros SKUs/Códigos Alternos',
        'product.field.department': 'Departamento',
        'product.field.family': 'Familia',
        'product.field.manufacturer': 'Manufacturero',
        'product.field.supplier': 'Suplidor Principal',
        'product.field.location': 'Localización Física',
        'product.field.creation_date': 'Fecha Creación',
        'product.field.material': 'Material',
        'product.field.quality': 'Calidad',
        'product.field.dimensions_weight': 'Dimensiones y Peso',
        'product.field.compatibility': 'Compatibilidad',
        'product.field.enable_price_levels': 'Activar múltiples niveles de precios para este producto',
        'product.field.price_level': 'Nivel',
        'product.field.price_levels_existing': 'Niveles Existentes',
        'product.field.enable_variations': 'Este producto tiene múltiples variaciones de venta',
        'product.field.variation_name': 'Nombre (ej: Metro)',
        'product.field.variation_price': 'Precio Venta',
        'product.field.variations_existing': 'Variaciones Existentes',
        'product.field.pos_display': 'Ilustrar en Pantalla (Botón en POS)',
        'product.field.pos_serial': 'Requiere Número de Serie en Venta',
        'product.field.pos_kitchen': 'Usar Impresora de Cocina',
        'product.field.pos_barcode': 'Usar Impresora de Código de Barras',
        'product.stock_total': 'Stock Total',
        'product.branch_units': 'Unidades',
        'product.price_levels': 'Niveles de Precios',
        'product.view_movement': 'Ver Movimiento',
        'product.calc_base': 'Cálculo de Precios (Base)',
        'product.customer_pays': 'Cliente Paga',
        'product.tax_rate': 'Tasa IVA (ej: 0.16)',
        'product.emergency_exempt': 'Aplicar Exención de Impuestos en Modo Emergencia',
        'product.discontinue': 'Descontinuar',
        'product.image_file': 'Archivo',
        'product.image_take': 'Sacar Foto',

        // Config Page
        'config.title': 'Configuración del Sistema',
        'config.subtitle': 'Ajuste las preferencias globales de la aplicación.',
        'config.regional': 'Preferencias Regionales',
        'config.timezone': 'Zona Horaria',
        'config.timezone_help': 'Esto afectará a los relojes del sistema y registros de fecha/hora.',
        'config.language': 'Idioma de la Interfaz',
        'config.number_format': 'Formato de Números',
        'config.appearance': 'Apariencia',
        'config.font_size': 'Tamaño de Fuente Global',
        'config.small': 'Pequeño',
        'config.medium': 'Mediano',
        'config.large': 'Grande',
        'config.preview': 'Vista Previa: El tamaño de la letra cambiará en toda la aplicación instantáneamente.',

        // Calendar
        'calendar.schedule_visit': 'Programar Visita',
        'calendar.visit': 'Visita',
        'calendar.project': 'Proyecto',
        'calendar.month': 'Mes',
        'calendar.week': 'Semana',
        'calendar.day': 'Día',
        'calendar.activity_for': 'Actividad para el',
        'calendar.no_activity': 'No hay actividades programadas.',
        'calendar.invalid_date': 'Fecha inválida',

        // Reports
        'reports.pm.title': 'Reportes de Gestión de Proyectos',
        'reports.pm.employee_performance': 'Desempeño y Carga de Colaboradores',
        'reports.pm.top_clients': 'Clientes Más Activos (Por Nº Proyectos)',
        'reports.pm.project_costs': 'Análisis de Costos Estimados',
        'reports.pm.completed_duration': 'Proyectos Completados: Duración Estimada',
        'reports.pm.pending_status': 'Proyectos Pendientes y Activos',
        'reports.col.employee': 'Colaborador',
        'reports.col.projects_count': '# Proyectos (A/P)',
        'reports.col.assigned_summary': 'Proyectos Asignados (Resumen)',
        'reports.col.client': 'Cliente',
        'reports.col.total_projects': '# Total Proj.',
        'reports.col.active_projects': '# Proy. (A/P)',
        'reports.col.project': 'Proyecto',
        'reports.col.est_cost': 'Costo Est.',
        'reports.col.duration': 'Duración Est.',
        'reports.col.next_activity': 'Próxima Actividad',
        'reports.col.resources': 'Recursos (P/E)',

        // POS Reports
        'reports.pos.title': 'Reportes de Punto de Venta',
        'reports.pos.net_sales': 'Ventas Netas',
        'reports.pos.total_returns': 'Total Devoluciones',
        'reports.pos.transactions': 'Transacciones',
        'reports.pos.avg_ticket': 'Ticket Promedio',
        'reports.pos.sales_by_register': 'Ventas por Caja (Turno Actual)',
        'reports.pos.returns_by_register': 'Devoluciones por Caja',
        'reports.pos.sales_by_method': 'Ventas por Método de Pago',
        'reports.pos.top_employees': 'Colaboradores con Más Ventas',
        'reports.pos.top_clients': 'Clientes Principales',
        'reports.pos.top_transactions': 'Ventas de Mayor Valor',
        'reports.pos.external_included': 'Cajas Externas Incluidas',
        'reports.pos.external_hidden': 'Cajas Externas Ocultas',
        'reports.filter.today': 'Hoy',
        'reports.filter.yesterday': 'Ayer',
        'reports.filter.this_month': 'Este Mes',
        'reports.filter.last_month': 'Mes Anterior',
        'reports.filter.custom': 'Personalizado',

        // E-commerce
        'ecommerce.settings.title': 'Configuración Global de E-commerce (Defaults)',
        'ecommerce.settings.subtitle': 'Estos ajustes se aplicarán como predeterminados para nuevas tiendas de clientes que no hayan personalizado su propia configuración.',
        'ecommerce.settings.store_name': 'Nombre de Tienda (Predeterminado)',
        'ecommerce.settings.logo_url': 'URL del Logo (Predeterminado)',
        'ecommerce.settings.template': 'Plantilla (Predeterminada)',
        'ecommerce.settings.primary_color': 'Color Primario (Predeterminado)',
        'ecommerce.settings.restore_defaults': 'Restaurar Defaults Maestros',
        'ecommerce.settings.save': 'Guardar Configuración Predeterminada',
        
        'ecommerce.orders.title': 'Gestión de Pedidos E-commerce',
        'ecommerce.orders.search_placeholder': 'Buscar por ID, cliente...',
        'ecommerce.orders.filter_status': 'Filtrar por estado de pedido',
        'ecommerce.orders.col.id': 'ID Pedido',
        'ecommerce.orders.col.date': 'Fecha',
        'ecommerce.orders.col.client': 'Cliente',
        'ecommerce.orders.col.total': 'Total',
        'ecommerce.orders.col.status': 'Estado',

        'ecommerce.suppliers.title': 'Gestión de Proveedores',
        'ecommerce.suppliers.create': 'Crear Proveedor',
        'ecommerce.suppliers.col.name': 'Nombre Proveedor',
        'ecommerce.suppliers.col.contact': 'Contacto',
        'ecommerce.suppliers.col.email': 'Email',
        'ecommerce.suppliers.col.phone': 'Teléfono',
        'ecommerce.suppliers.form.create_title': 'Crear Proveedor',
        'ecommerce.suppliers.form.edit_title': 'Editar Proveedor',
        'ecommerce.suppliers.form.name': 'Nombre del Proveedor',
        'ecommerce.suppliers.form.contact': 'Nombre de Contacto (Opcional)',
        'ecommerce.suppliers.form.email': 'Email',
        'ecommerce.suppliers.form.phone': 'Teléfono (Opcional)',
        'ecommerce.suppliers.form.address': 'Dirección (Opcional)',

        'ecommerce.supplier_orders.title': 'Pedidos a Proveedores',
        'ecommerce.supplier_orders.search_placeholder': 'Buscar por ID, proveedor...',
        'ecommerce.supplier_orders.create': 'Crear Pedido',
        'ecommerce.supplier_orders.col.id': 'ID Pedido',
        'ecommerce.supplier_orders.col.supplier': 'Proveedor',
        'ecommerce.supplier_orders.col.date': 'Fecha Pedido',
        'ecommerce.supplier_orders.col.delivery_date': 'F. Entrega Est.',
        'ecommerce.supplier_orders.col.cost': 'Costo Total',
        'ecommerce.supplier_orders.col.status': 'Estado',
        'ecommerce.supplier_orders.form.create_title': 'Crear Pedido a Proveedor',
        'ecommerce.supplier_orders.form.edit_title': 'Editar Pedido a Proveedor',
        'ecommerce.supplier_orders.form.items': 'Artículos del Pedido',
        'ecommerce.supplier_orders.form.item_product': 'Producto',
        'ecommerce.supplier_orders.form.item_quantity': 'Cantidad',
        'ecommerce.supplier_orders.form.item_cost': 'Costo Unit.',
        'ecommerce.supplier_orders.form.add_item': 'Añadir Artículo',
    },
    en: {
        // Common
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.create': 'Create',
        'common.search': 'Search',
        'common.actions': 'Actions',
        'common.name': 'Name',
        'common.email': 'Email',
        'common.phone': 'Phone',
        'common.address': 'Address',
        'common.accept': 'Accept',
        'common.confirm': 'Confirm',
        'common.status': 'Status',
        'common.notes': 'Notes',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.import_ai': 'Import with AI',
        'common.previous': 'Previous',
        'common.next': 'Next',
        'common.page_of': 'Page {current} of {total}',
        'common.today': 'Today',
        'common.error': 'Error',
        'common.date': 'Date',
        'common.total': 'Total',
        'common.client': 'Client',
        'common.add': 'Add',
        'common.update': 'Update',
        'common.loading': 'Loading...',
        'common.go_back': 'Go Back',
        'common.hours': 'hours',

        // Dashboard Home
        'dashboard.welcome': 'Welcome to Pazzi',
        'dashboard.select_module': 'Select a module to start working.',
        'dashboard.quick_access': 'Quick Access',
        'dashboard.desc.tienda': 'Manage products, clients, inventory, and branches.',
        'dashboard.desc.pm': 'Manage projects, resources, and schedules.',
        'dashboard.desc.pos': 'Point of sale, cash register, and billing.',
        'dashboard.desc.ecommerce': 'Online store administration and orders.',
        'dashboard.desc.admin': 'Global configuration and alerts.',
        'dashboard.desc.client': 'Client portal.',
        'dashboard.access_btn': 'Access {module} tools',

        // Dashboard Tour
        'tour.step1.title': 'Welcome to Pazzi',
        'tour.step1.content': 'This is a brief tour of the main modules. Use the module selector or sidebar to navigate.',
        'tour.step2.title': 'Project Management',
        'tour.step2.content': 'Manage projects, clients, resources, calendars, and communication.',
        'tour.step3.title': 'Point of Sale (POS)',
        'tour.step3.content': 'Make sales, manage cash, inventory, and reports in-store.',
        'tour.step4.title': 'E-commerce Admin',
        'tour.step4.content': 'Configure your online store, manage web products, and orders.',
        'tour.step5.title': 'All Set!',
        'tour.step5.content': 'You have completed the tour. Explore Pazzi and discover everything it can do for your business!',
        'tour.skip': 'Skip Tour',
        'tour.finish': 'Finish',

        // Admin Dashboard
        'admin.dashboard.title': 'Administration Panel',
        'admin.dashboard.subtitle': 'Configure global options and system alerts.',

        // Navbar & User Menu
        'nav.my_account': 'My Account',
        'nav.configuration': 'Configuration',
        'nav.logout': 'Log Out',
        'nav.my_orders': 'My Orders',

         // Modules Names (English)
        'Tienda': 'Store',
        'Gestión de Proyectos': 'Project Management',
        'Punto de Venta': 'Point of Sale',
        'E-commerce': 'E-commerce',
        'Administración': 'Administration',
        'Portal Cliente': 'Client Portal',

        // Submodules Names (English)
        'Productos': 'Products',
        'Inventario': 'Inventory',
        'Categorías': 'Categories',
        'Departamentos': 'Departments',
        'Clientes': 'Clients',
        'Colaboradores': 'Employees',
        'Sucursales': 'Branches',
        'Dashboard PM': 'PM Dashboard',
        'Proyectos': 'Projects',
        'Chat de Proyectos': 'Project Chat',
        'Calendario': 'Calendar',
        'Reportes PM': 'PM Reports',
        'Caja Registradora': 'Cash Register',
        'Reportes POS': 'POS Reports',
        'Historial de Ventas': 'Sales History',
        'Estimados': 'Estimates',
        'Apartados (Layaway)': 'Layaways',
        'Cuentas por Cobrar': 'Accounts Receivable',
        'Cuentas por Pagar': 'Accounts Payable',
        'Config. Cajas': 'Register Config',
        'Dashboard E-commerce': 'E-commerce Dashboard',
        'Pedidos Online': 'Online Orders',
        'Proveedores': 'Suppliers',
        'Pedidos a Proveedor': 'Supplier Orders',
        'Mi Tienda (Vista Previa)': 'My Store (Preview)',
        'Dashboard Admin': 'Admin Dashboard',
        'Dashboard Cliente': 'Client Dashboard',
        'Calendario Proyecto': 'Project Calendar',
        'Chat del Proyecto': 'Project Chat',

        // Quick Links (English)
        'quick.create_product': 'Create Product',
        'quick.sales_history': 'Sales History',
        'quick.view_projects': 'View Projects',
        'quick.view_inventory': 'View Inventory',
        'quick.go_to_pos': 'Go to Register',
        'quick.my_projects': 'My Projects',

        // PM Dashboard Specifics
        'pm.dashboard.title': 'Project Dashboard',
        'pm.dashboard.subtitle': 'A summary of recent and upcoming activity.',
        'pm.dashboard.view_all': 'View All Projects',
        'pm.dashboard.full_calendar': 'Full Calendar',
        'pm.stats.active': 'Active Projects',
        'pm.stats.pending': 'Pending Projects',
        'pm.stats.completed_month': 'Completed (This Month)',
        'pm.section.in_progress': 'Projects In Progress or Upcoming',
        'pm.section.visits': 'Upcoming Visits',
        'pm.section.top_clients': 'Top Clients (This Month)',
        'pm.section.recent_chat': 'Recent Chat Activity',
        'pm.section.top_employees': 'Most Active Employees (This Month)',
        'pm.no_client': 'No client assigned',
        'pm.view_chat': 'View Chat',
        'pm.no_active_projects': 'No active or upcoming projects.',
        'pm.general_visit': 'General Visit',
        'pm.no_visits': 'No visits scheduled.',
        'pm.no_sales': 'No client sales data for this month.',
        'pm.no_messages': 'No recent messages.',
        'pm.no_hours': 'No visit hours recorded this month.',

        // Project Detail
        'project.detail.back': 'Back to Projects',
        'project.detail.not_found': 'Project not found',
        'project.detail.not_found_desc': 'The project you are looking for does not exist or has been deleted.',
        'project.detail.back_list': 'Back to project list',
        'project.detail.create_title': 'Create New Project',

        // Tasks
        'tasks.status.todo': 'To Do',
        'tasks.status.in_progress': 'In Progress',
        'tasks.status.for_approval': 'For Approval',
        'tasks.status.done': 'Done',
        'tasks.add_placeholder': 'Type a title for this task...',
        'tasks.add_btn': 'Add Task',
        'tasks.add_trigger': 'Add a task',
        'tasks.detail.title': 'Task Details',
        'tasks.detail.field_title': 'Title',
        'tasks.detail.field_desc': 'Description',
        'tasks.detail.desc_placeholder': 'Add a more detailed description...',
        'tasks.detail.assignees': 'Assign Employees',
        'tasks.detail.comments': 'Comments',
        'tasks.detail.no_comments': 'No comments.',
        'tasks.detail.comment_placeholder': 'Add a comment...',
        'tasks.detail.archive': 'Archive Task',
        'tasks.detail.confirm_archive': 'Are you sure you want to archive this task?',

        // Inventory Page
        'inventory.title': 'Inventory Management',
        'inventory.search_placeholder': 'Search by name or SKU...',
        'inventory.filter.all_categories': 'All Categories',
        'inventory.col.product': 'Product',
        'inventory.col.total_stock': 'Total Stock',
        'inventory.action.history': 'History',
        'inventory.action.adjust': 'Adjust Stock',
        
        // Inventory History
        'inventory.history.title': 'Inventory History: {product}',
        'inventory.history.current_stock_branch': 'Current Stock by Branch',
        'inventory.history.total': 'Total',
        'inventory.history.movement_log': 'Movement Log by Branch',
        'inventory.history.col_date': 'Date',
        'inventory.history.col_type': 'Type',
        'inventory.history.col_change': 'Change',
        'inventory.history.col_stock_before': 'Stock Before',
        'inventory.history.col_stock_after': 'Stock After',
        'inventory.history.col_ref': 'Ref.',
        'inventory.history.col_notes': 'Notes',
        'inventory.history.col_employee': 'Employee',
        'inventory.history.no_movements': 'No movements recorded for this product in this branch.',

        // Stock Adjustment
        'inventory.adjust.title': 'Manage Stock for: {product}',
        'inventory.adjust.single_title': 'Adjust Stock - {product}',
        'inventory.adjust.adjusting_for': 'Adjusting stock for {product} in branch {branch}.',
        'inventory.adjust.stock_in_branch': 'Stock in branch ({branch})',
        'inventory.adjust.total_stock_all': 'Total Stock (all branches)',
        'inventory.adjust.help_text': 'Enter quantity to add (e.g., 10 or +10) or subtract (e.g., -5) for each branch. Leave blank if no change.',
        'inventory.adjust.col_branch': 'Branch',
        'inventory.adjust.col_current': 'Current Stock',
        'inventory.adjust.col_adjust': 'Adjustment (+/-)',
        'inventory.adjust.col_new': 'New Stock',
        'inventory.adjust.col_notes': 'Notes',
        'inventory.adjust.save': 'Save Adjustments',
        'inventory.adjust.save_btn': 'Save Adjustment',
        'inventory.adjust.add_subtract': 'Add or Subtract Stock',
        'inventory.adjust.input_placeholder': 'E.g., +10, -5, 25',
        'inventory.adjust.input_help': 'Enter quantity to add (e.g. 10 or +10) or subtract (e.g. -5).',
        'inventory.adjust.new_stock': 'New Stock in Branch',
        'inventory.adjust.reason_label': 'Notes / Reason (Optional but Recommended)',
        'inventory.adjust.reason_placeholder': 'E.g., Physical count, damaged product, transfer...',

        // Categories
        'category.list.title': 'Category Management',
        'category.list.create': 'Create Category',
        'category.form.create': 'Create Category',
        'category.form.edit': 'Edit Category',
        'category.field.name': 'Category Name',

        // Departments
        'department.list.title': 'Department Management',
        'department.list.create': 'Create Department',
        'department.form.create': 'Create Department',
        'department.form.edit': 'Edit Department',
        'department.field.name': 'Department Name',

        // Branches
        'branch.list.title': 'Branch Management',
        'branch.list.create': 'Create Branch',
        'branch.form.create': 'Create Branch',
        'branch.form.edit': 'Edit Branch',
        'branch.field.name': 'Branch Name',
        'branch.field.address': 'Address',
        'branch.field.phone': 'Phone',
        'branch.field.active': 'Active Branch',

        // Employees
        'employee.list.title': 'Employee Management',
        'employee.list.create': 'Create Employee',
        'employee.form.create': 'Create Employee',
        'employee.form.edit': 'Edit Employee',
        'employee.field.name': 'Name',
        'employee.field.lastname': 'Last Name',
        'employee.field.email': 'Email',
        'employee.field.role': 'Role',
        'employee.field.phone': 'Phone',
        'employee.field.address': 'Address',
        'employee.tab.personal': 'Personal',
        'employee.tab.access': 'Access & Employment',
        'employee.tab.permissions': 'Permissions',
        'employee.tab.info': 'Additional Info',

        // Clients
        'client.list.title': 'Client Management',
        'client.list.create': 'Create Client',
        'client.form.create': 'Create Client',
        'client.form.edit': 'Modify Client',
        'client.field.lastname': 'Last Name',
        'client.field.type': 'Type',
        'client.field.company': 'Company',
        'client.field.city': 'City',
        'client.field.country': 'Country',
        'client.field.zip': 'Zip',
        'client.field.fax': 'Fax',
        'client.field.contact_person': 'Contact Person',
        'client.field.ssn': 'Social Security',
        'client.field.dob': 'Date of Birth',
        'client.field.projects': 'Associated Projects',
        'client.field.projects_hint': 'Hold Ctrl (or Cmd on Mac) to select multiple projects.',
        'client.tab.general': 'General',
        'client.tab.taxes': 'Taxes',
        'client.tab.billing': 'Billing',
        'client.tab.payments': 'Payments',
        'client.tab.shipping': 'Shipping',
        'client.tab.loyalty': 'Loyalty',
        'client.tab.photo': 'Photo',
        
        // Client Tabs Details
        'client.taxes.responsibility': 'Tax Responsibility',
        'client.taxes.state': 'State (%)',
        'client.taxes.municipal': 'Municipal (%)',
        'client.taxes.tax_id': 'Tax ID (RFC/NIF)',
        'client.taxes.exemption': 'Municipal Tax Exemption - Valid Until',
        'client.billing.address': 'Billing Address',
        'client.billing.special_msg': 'Special Message on Invoice',
        'client.billing.special_msg_hint': 'The message can be configured in: Maintenance - Options.',
        'client.billing.charge_type': 'Agreed Charge Type',
        'client.billing.discount_price': 'Discount on Price',
        'client.billing.markup_cost': 'Markup on Cost',
        'client.billing.code': 'Password/Code',
        'client.payments.balance': 'Balance',
        'client.payments.credit_limit': 'Credit Limit',
        'client.payments.terms': 'Terms',
        'client.payments.category': 'Category',
        'client.payments.salesperson': 'Salesperson',
        'client.payments.price_level': 'Price Level',
        'client.payments.business_type': 'Business Type',
        'client.payments.zone': 'Zone',
        'client.payments.show_balance': 'Show Balance',
        'client.shipping.address': 'Shipping Address',
        'client.shipping.contact_name': 'Shipping Contact Name',
        'client.shipping.contact_phone': 'Shipping Contact Phone',
        'client.shipping.carrier': 'Preferred Carrier',
        'client.loyalty.points': 'Loyalty Points',
        'client.loyalty.level': 'Loyalty Level',
        'client.photo.add_url': 'Add Image URL',

        // Projects
        'project.list.title': 'Project Management',
        'project.list.create': 'Create Project',
        'project.form.create': 'Create Project',
        'project.form.edit': 'Edit Project',
        'project.tab.details': 'Details',
        'project.tab.schedule': 'Schedule',
        'project.tab.resources': 'Resources',
        'project.tab.invoicing': 'Invoicing',
        'project.tab.chat': 'Project Chat',
        'project.tab.tasks': 'Tasks',
        'project.field.name': 'Project Name',
        'project.field.client': 'Client',
        'project.field.status': 'Status',
        'project.field.description': 'Description',
        'project.field.team': 'Assigned Team',
        'project.field.next_visit': 'Next Visit',
        
        // Project Schedule
        'project.schedule.initial_visit': 'Initial Visit',
        'project.schedule.visit_date': 'Visit Date',
        'project.schedule.visit_time': 'Visit Time',
        'project.schedule.work_type': 'Project Work',
        'project.schedule.mode.days_only': 'Days Only',
        'project.schedule.mode.days_times': 'Days and Times',
        'project.schedule.mode.range': 'Continuous Range',
        'project.schedule.add_work_day': 'Add Work Day',
        'project.schedule.start_time': 'Start Time',
        'project.schedule.end_time': 'End Time',
        'project.schedule.add_range': 'Add Range',
        'project.schedule.range_start': 'Range Start Date',
        'project.schedule.range_end': 'Range End Date',

        // Project Resources
        'project.resources.assign_catalog': 'Assign Catalog Products',
        'project.resources.add_custom_title': 'Add Custom Product/Service',
        'project.resources.quantity': 'Quantity',
        'project.resources.unit_price_opt': 'Unit Price (Opt)',
        'project.resources.add_custom_btn': 'Add Custom',
        'project.resources.assign_employees': 'Assign Employees',
        'project.resources.custom_name': 'Name (e.g. Extra Material)',

        // POS
        'pos.title': 'Main Register',
        'pos.emergency_mode': 'Emergency Mode',
        'pos.clear_cart': 'Clear',
        'pos.hold_cart': 'Hold',
        'pos.client': 'Client',
        'pos.payout': 'Payout',
        'pos.return': 'Return',
        'pos.estimate': 'Estimate',
        'pos.layaway': 'Layaway',
        'pos.reprint': 'Reprint',
        'pos.close_shift': 'Close Shift',
        'pos.user': 'User',
        'pos.pay': 'Pay',
        'pos.total': 'TOTAL',
        'pos.subtotal': 'Subtotal',
        'pos.tax': 'Tax',
        'pos.search_placeholder': 'Search by SKU, Barcode, or Name',
        'pos.empty_cart': 'Cart is empty',
        'pos.client_search': 'Search / Assign Client',
        'pos.new_project': 'New Project',
        'pos.header.external': 'EXTERNAL',
        
        // POS Sales History
        'pos.sales_history.title': 'POS Sales History',
        'pos.sales_history.col.id': 'Sale ID',
        'pos.sales_history.col.date': 'Date',
        'pos.sales_history.col.total': 'Total',
        'pos.sales_history.col.items': 'Items',
        'pos.sales_history.col.method': 'Payment Method',
        'pos.sales_history.col.cashier': 'Cashier',
        'pos.sales_history.col.register': 'Register ID',
        'pos.sales_history.print_receipt': 'Print Receipt',

        // POS Estimates
        'pos.estimates.title': 'Estimates Management',
        'pos.estimates.create': 'Create Estimate',
        'pos.estimates.combine': 'Combine',
        'pos.estimates.col.id': 'Estimate ID',
        'pos.estimates.col.date': 'Date',
        'pos.estimates.col.client': 'Client',
        'pos.estimates.col.total': 'Total',
        'pos.estimates.col.status': 'Status',
        'pos.estimates.form.create_title': 'Create Estimate',
        'pos.estimates.form.edit_title': 'Edit Estimate',
        'pos.estimates.form.add_products': 'Add Products',
        'pos.estimates.form.status': 'Status',
        'pos.estimates.form.valid_until': 'Valid Until (Optional)',
        'pos.estimates.form.notes': 'Notes',
        'pos.estimates.print_pdf': 'Print PDF',
        'pos.estimates.confirm_combine.title': 'Confirm Combine Estimates',
        'pos.estimates.confirm_combine.message': 'Are you sure you want to combine {count} estimates into a new one? The original estimates will be marked as "Combined".',

        // POS Layaways
        'pos.layaways.title': 'Layaway Management',
        'pos.layaways.col.id': 'Layaway ID',
        'pos.layaways.col.date': 'Date',
        'pos.layaways.col.client': 'Client',
        'pos.layaways.col.total': 'Total',
        'pos.layaways.col.paid': 'Paid',
        'pos.layaways.col.balance': 'Balance',
        'pos.layaways.col.status': 'Status',
        'pos.layaways.register_payment': 'Register Payment',
        'pos.layaways.mark_completed': 'Mark as Completed/Delivered',
        'pos.layaways.cancel': 'Cancel Layaway',
        'pos.layaways.confirm_cancel.title': 'Confirm Layaway Cancellation',
        'pos.layaways.confirm_cancel.message': 'Are you sure you want to cancel layaway #{id}? Stock will NOT be returned automatically.',
        'pos.layaways.confirm_complete.title': 'Confirm Completion',
        'pos.layaways.confirm_complete.message': 'Mark layaway #{id} as completed and delivered?',
        
        // POS Accounts Receivable
        'pos.receivable.title': 'Accounts Receivable',
        'pos.receivable.filter': 'Filter:',
        'pos.receivable.filter.pending': 'Pending',
        'pos.receivable.filter.paid': 'Paid',
        'pos.receivable.filter.all': 'All',
        'pos.receivable.col.id': 'Sale ID',
        'pos.receivable.col.date': 'Sale Date',
        'pos.receivable.col.due_date': 'Due Date',
        'pos.receivable.col.client': 'Client',
        'pos.receivable.col.total': 'Total Amount',
        'pos.receivable.col.paid': 'Amount Paid',
        'pos.receivable.col.balance': 'Balance',
        'pos.receivable.col.status': 'Status',
        'pos.receivable.action.reminder': 'Send Reminder',
        'pos.receivable.action.edit': 'Edit Details',
        'pos.receivable.action.print': 'Print Bill',
        'pos.receivable.action.payment': 'Register Payment',
        'pos.receivable.action.void': 'Void Bill',
        'pos.receivable.payment_modal.title': 'Register Payment for Sale #{id}',
        'pos.receivable.payment_modal.balance': 'Pending Balance',
        'pos.receivable.payment_modal.amount': 'Payment Amount',
        'pos.receivable.payment_modal.method': 'Payment Method',
        'pos.receivable.payment_modal.reference': 'Invoice/Reference # (Optional)',
        'pos.receivable.payment_modal.attachment': 'Attach Receipt (Optional)',
        'pos.receivable.payment_modal.register': 'Register Payment',
        'pos.receivable.edit_modal.title': 'Edit Account Receivable - Sale #{id}',
        'pos.receivable.edit_modal.client': 'Client',
        'pos.receivable.edit_modal.original_amount': 'Original Amount',
        'pos.receivable.edit_modal.due_date': 'Due Date',
        'pos.receivable.edit_modal.notes': 'Collection Notes',
        'pos.receivable.confirm_reminder.title': 'Send Collection Notification',
        'pos.receivable.confirm_reminder.message': 'Are you sure you want to send a collection notification message to client {client}?',
        'pos.receivable.confirm_reminder.btn': 'Yes, Send Message',
        'pos.receivable.confirm_void.title': 'Confirm Void',
        'pos.receivable.confirm_void.message': 'Are you sure you want to void account receivable {id}?',
        'pos.receivable.confirm_void.btn': 'Yes, Void',

        // Product Page & Modal
        'product.list.title': 'Product Management',
        'product.list.add': 'Add Product',
        'product.list.import_ai': 'Import with AI',
        'product.form.title.create': 'Create Product',
        'product.form.title.edit': 'Modify Inventory',
        'product.tab.main': 'Main',
        'product.tab.inventory': 'Inventory & Pricing',
        'product.tab.identification': 'Identification',
        'product.tab.classification': 'Classification',
        'product.tab.specs': 'Specifications',
        'product.tab.prices': 'Price Levels',
        'product.tab.variations': 'Variations',
        'product.tab.pos': 'POS Config',
        'product.field.name': 'Name',
        'product.field.sku': 'Reference (SKU)',
        'product.field.barcode': 'Barcode',
        'product.field.price': 'Base Price',
        'product.field.cost': 'Cost',
        'product.field.profit': 'Profit',
        'product.field.inventory': 'Inventory',
        'product.field.available': 'Available',
        'product.field.category': 'Category',
        'product.field.description': 'Description',
        'product.field.active': 'Active',
        'product.field.service': 'Service',
        'product.field.supplier_code': 'Supplier Inv Code',
        'product.field.chain_code': 'Chain Code',
        'product.field.other_skus': 'Other SKUs/Alt Codes',
        'product.field.department': 'Department',
        'product.field.family': 'Family',
        'product.field.manufacturer': 'Manufacturer',
        'product.field.supplier': 'Main Supplier',
        'product.field.location': 'Physical Location',
        'product.field.creation_date': 'Creation Date',
        'product.field.material': 'Material',
        'product.field.quality': 'Quality',
        'product.field.dimensions_weight': 'Dimensions & Weight',
        'product.field.compatibility': 'Compatibility',
        'product.field.enable_price_levels': 'Enable multiple price levels for this product',
        'product.field.price_level': 'Level',
        'product.field.price_levels_existing': 'Existing Levels',
        'product.field.enable_variations': 'This product has multiple sales variations',
        'product.field.variation_name': 'Name (e.g. Meter)',
        'product.field.variation_price': 'Sales Price',
        'product.field.variations_existing': 'Existing Variations',
        'product.field.pos_display': 'Show on Screen (POS Button)',
        'product.field.pos_serial': 'Requires Serial Number on Sale',
        'product.field.pos_kitchen': 'Use Kitchen Printer',
        'product.field.pos_barcode': 'Use Barcode Printer',
        'product.stock_total': 'Total Stock',
        'product.branch_units': 'Units',
        'product.price_levels': 'Price Levels',
        'product.view_movement': 'View Movement',
        'product.calc_base': 'Price Calculation (Base)',
        'product.customer_pays': 'Customer Pays',
        'product.tax_rate': 'Tax Rate (e.g. 0.16)',
        'product.emergency_exempt': 'Apply Tax Exemption in Emergency Mode',
        'product.discontinue': 'Discontinue',
        'product.image_file': 'File',
        'product.image_take': 'Take Photo',

        // Config Page
        'config.title': 'System Configuration',
        'config.subtitle': 'Adjust global application preferences.',
        'config.regional': 'Regional Preferences',
        'config.timezone': 'Timezone',
        'config.timezone_help': 'This will affect system clocks and date/time logs.',
        'config.language': 'Interface Language',
        'config.number_format': 'Number Format',
        'config.appearance': 'Appearance',
        'config.font_size': 'Global Font Size',
        'config.small': 'Small',
        'config.medium': 'Medium',
        'config.large': 'Large',
        'config.preview': 'Preview: The font size will change across the application instantly.',

        // Calendar
        'calendar.schedule_visit': 'Schedule Visit',
        'calendar.visit': 'Visit',
        'calendar.project': 'Project',
        'calendar.month': 'Month',
        'calendar.week': 'Week',
        'calendar.day': 'Day',
        'calendar.activity_for': 'Activity for',
        'calendar.no_activity': 'No activities scheduled.',
        'calendar.invalid_date': 'Invalid date',

        // Reports
        'reports.pm.title': 'Project Management Reports',
        'reports.pm.employee_performance': 'Employee Performance & Load',
        'reports.pm.top_clients': 'Most Active Clients (By # Projects)',
        'reports.pm.project_costs': 'Estimated Cost Analysis',
        'reports.pm.completed_duration': 'Completed Projects: Estimated Duration',
        'reports.pm.pending_status': 'Pending & Active Projects',
        'reports.col.employee': 'Employee',
        'reports.col.projects_count': '# Projects (A/P)',
        'reports.col.assigned_summary': 'Assigned Projects (Summary)',
        'reports.col.client': 'Client',
        'reports.col.total_projects': '# Total Proj.',
        'reports.col.active_projects': '# Proj. (A/P)',
        'reports.col.project': 'Project',
        'reports.col.est_cost': 'Est. Cost',
        'reports.col.duration': 'Est. Duration',
        'reports.col.next_activity': 'Next Activity',
        'reports.col.resources': 'Resources (P/E)',

        // POS Reports
        'reports.pos.title': 'Point of Sale Reports',
        'reports.pos.net_sales': 'Net Sales',
        'reports.pos.total_returns': 'Total Returns',
        'reports.pos.transactions': 'Transactions',
        'reports.pos.avg_ticket': 'Avg. Ticket',
        'reports.pos.sales_by_register': 'Sales by Register (Current Shift)',
        'reports.pos.returns_by_register': 'Returns by Register',
        'reports.pos.sales_by_method': 'Sales by Payment Method',
        'reports.pos.top_employees': 'Top Selling Employees',
        'reports.pos.top_clients': 'Top Clients',
        'reports.pos.top_transactions': 'Highest Value Transactions',
        'reports.pos.external_included': 'External Registers Included',
        'reports.pos.external_hidden': 'External Registers Hidden',
        'reports.filter.today': 'Today',
        'reports.filter.yesterday': 'Yesterday',
        'reports.filter.this_month': 'This Month',
        'reports.filter.last_month': 'Last Month',
        'reports.filter.custom': 'Custom',

        // E-commerce
        'ecommerce.settings.title': 'E-commerce Global Configuration (Defaults)',
        'ecommerce.settings.subtitle': 'These settings will apply as defaults for new client stores that have not customized their configuration.',
        'ecommerce.settings.store_name': 'Store Name (Default)',
        'ecommerce.settings.logo_url': 'Logo URL (Default)',
        'ecommerce.settings.template': 'Template (Default)',
        'ecommerce.settings.primary_color': 'Primary Color (Default)',
        'ecommerce.settings.restore_defaults': 'Restore Master Defaults',
        'ecommerce.settings.save': 'Save Default Configuration',
        
        'ecommerce.orders.title': 'E-commerce Orders Management',
        'ecommerce.orders.search_placeholder': 'Search by ID, client...',
        'ecommerce.orders.filter_status': 'Filter by order status',
        'ecommerce.orders.col.id': 'Order ID',
        'ecommerce.orders.col.date': 'Date',
        'ecommerce.orders.col.client': 'Client',
        'ecommerce.orders.col.total': 'Total',
        'ecommerce.orders.col.status': 'Status',

        'ecommerce.suppliers.title': 'Supplier Management',
        'ecommerce.suppliers.create': 'Create Supplier',
        'ecommerce.suppliers.col.name': 'Supplier Name',
        'ecommerce.suppliers.col.contact': 'Contact',
        'ecommerce.suppliers.col.email': 'Email',
        'ecommerce.suppliers.col.phone': 'Phone',
        'ecommerce.suppliers.form.create_title': 'Create Supplier',
        'ecommerce.suppliers.form.edit_title': 'Edit Supplier',
        'ecommerce.suppliers.form.name': 'Supplier Name',
        'ecommerce.suppliers.form.contact': 'Contact Name (Optional)',
        'ecommerce.suppliers.form.email': 'Email',
        'ecommerce.suppliers.form.phone': 'Phone (Optional)',
        'ecommerce.suppliers.form.address': 'Address (Optional)',

        'ecommerce.supplier_orders.title': 'Supplier Orders',
        'ecommerce.supplier_orders.search_placeholder': 'Search by ID, supplier...',
        'ecommerce.supplier_orders.create': 'Create Order',
        'ecommerce.supplier_orders.col.id': 'Order ID',
        'ecommerce.supplier_orders.col.supplier': 'Supplier',
        'ecommerce.supplier_orders.col.date': 'Order Date',
        'ecommerce.supplier_orders.col.delivery_date': 'Est. Delivery',
        'ecommerce.supplier_orders.col.cost': 'Total Cost',
        'ecommerce.supplier_orders.col.status': 'Status',
        'ecommerce.supplier_orders.form.create_title': 'Create Supplier Order',
        'ecommerce.supplier_orders.form.edit_title': 'Edit Supplier Order',
        'ecommerce.supplier_orders.form.items': 'Order Items',
        'ecommerce.supplier_orders.form.item_product': 'Product',
        'ecommerce.supplier_orders.form.item_quantity': 'Quantity',
        'ecommerce.supplier_orders.form.item_cost': 'Unit Cost',
        'ecommerce.supplier_orders.form.add_item': 'Add Item',
    }
};

export const GlobalSettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [settings, setSettings] = useState<GlobalSettings>(() => {
        const stored = localStorage.getItem('pazziGlobalSettings');
        return stored ? JSON.parse(stored) : DEFAULT_SETTINGS;
    });

    const updateSettings = (newSettings: Partial<GlobalSettings>) => {
        setSettings(prev => {
            const updated = { ...prev, ...newSettings };
            localStorage.setItem('pazziGlobalSettings', JSON.stringify(updated));
            return updated;
        });
    };

    const t = (key: string, params?: Record<string, string | number>) => {
        const lang = (settings.language || 'es') as keyof typeof TRANSLATIONS;
        // @ts-ignore
        let text = TRANSLATIONS[lang][key] || key;
        
        if (params) {
            Object.entries(params).forEach(([k, v]) => {
                text = text.replace(`{${k}}`, String(v));
            });
        }
        return text;
    };

    return (
        <GlobalSettingsContext.Provider value={{ settings, updateSettings, t }}>
            {children}
        </GlobalSettingsContext.Provider>
    );
};

export const useGlobalSettings = () => {
    const context = useContext(GlobalSettingsContext);
    if (!context) throw new Error('useGlobalSettings must be used within a GlobalSettingsProvider');
    return context;
};

export const useTranslation = () => {
    const { t, settings } = useGlobalSettings();
    return { t, lang: settings.language };
};
